trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Npm@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      command: "custom"
      customCommand: "install --legacy-peer-deps"
  - task: Npm@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      command: "custom"
      customCommand: "run build"
  - task: npmAuthenticate@0
    inputs:
      workingFile: ".npmrc"
  - task: Npm@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      command: "publish"
      publishRegistry: "useFeed"
      publishFeed: "d7bdf2f6-a624-45ce-a264-701f6ff0cc3f/5d21d636-4e4f-4ae5-babf-051c32637bc1"
